### ISSUE TITLE
How to handle updates

### ISSUE THREAD

**Issue by danielegobbetti** [noi-techpark/sfscon-maps#5]
As of now the application is at version (sha commit id) [897cf68c](https://github.com/noi-techpark/sfscon-maps/blob/58bc51082c65509c36698ed5445f58403b4fa565/.github/workflows/cicd.yml#L27). The development instance and the testing (and later production) instances must be kept aligned as database dumps and imports are the [only](https://github.com/c3nav/c3nav/issues/193#issuecomment-2311090238) [officially](https://github.com/c3nav/c3nav/blob/main/deployment/docker/loadproduction_docker.sh) [supported](https://github.com/c3nav/c3nav/blob/main/deployment/docker/db_export.sh) [way](https://github.com/c3nav/c3nav/blob/main/deployment/docker/db_import.sh) of keeping instances updated.

We should agree on a workflow to keep the app updated.

**Comment by clezag** [comment]
@danielegobbetti privacy considerations permitting (or using encryption), we could include the dumps in this repo and set up a CI/CD chain that loads it in tandem with the application deploy. 

We could provision a separate schema/db per version, or a new docker volume every time, so we can go back if something goes wrong.

**Comment by clezag** [comment]
@danielegobbetti since we're now going into production (#9) it's probably time to figure this out.
Could putting the dump under version control work? 

e.g. Just put the dump into the repo, and modify the compose config to load a sql script on database startup.
Since the DB will also contain user data that has to persist between upgrades, how did you handle that until now?

**Comment by danielegobbetti** [comment]
@clezag here a couple of options:

we could dump the database using the flag ``--exclude-table-data=public.auth_user`` of pgdump: this would keep the database schema intact (including the user information) but not publish include the actual users' records. Thus the file could be added to this repository **assuming we have an appropriate license to attach to it (I guess this is a question for @sseppi )**.  The latest dump (in sql format) is 10114 rows / ~470 Kb so I believe it would be manageable under version control.

As you mentioned privacy considerations, currently the database holds one user record of the administrative user, and the password is stored as ``pbkdf2_sha256`` hash. Further information are a user name and an email address.

Now that there are two instances running, I'd suggest we try upgrading the one in testing as there are a couple of interesting new settings related to branding and mobile app references.
Let me know if you prefer we test the upgrade and I should upload the database separately as I did until now, or if you prefer to test both changes at the same time.

**Comment by clezag** [comment]
@danielegobbetti If there is only the one user table, that's perfect. I'd say we do as you proposed and exclude it in the dump. 
I will create a clean dump, excluding the table you mentioned, and extend CI/CD to load the dump on deploy.
Once that's working, you can use it to test the upgrade process.

Also what's your opinion on moving to an RDS instance? 
Do we even need that at this point? 
Isn't the only persistent thing the sole admin user? 
As I understood it, users will not be able to create accounts themselves

**Comment by danielegobbetti** [comment]
For reference (database name / other references might need adjustments):
``pg_dump c3navdatabase -c --if-exists --no-owner --no-privileges --exclude-table-data=public.auth_user``

We disabled user creation in the app's settings, but I guess the final call is on the sfscon team.

**Comment by clezag** [comment]
I've set up CI/CD to load the dump after deploying the application, and also moved the magic incantations to regenerate the cache there. The db directory contains a dump.sql that gets loaded after deploy.

N.B: When generating the dump, I had to exclude the whole table, not just the data with `--exclude-table`, because otherwise it still generated the `drop table` statements. I've left the script in the `/db` directory. 
_seems like I forgot to add `--no-privileges`, but you get the gist_

**Comment by danielegobbetti** [comment]
> N.B: When generating the dump, I had to exclude the whole table, not just the data with `--exclude-table`, because otherwise it still generated the `drop table` statements. I've left the script in the `/db` directory. _seems like I forgot to add `--no-privileges`, but you get the gist_

Doesn't this mean that the ``auth_user`` table would be missing when deploying the database from scratch? I don't know how the application would react to this

**Comment by clezag** [comment]
Yes, creating it from scratch from the dump would have this issue, but even if you included the table metadata, you'd still be missing the admin user record, probably tripping some constraints. 

I don't know how the DB is initialized in the first place, is the admin user generated by django on first startup? In that case it should even be fine, since the dump gets loaded afterwards. 

The `dump.sql` is a single one, the idea is that what's in prod and testing is managed by the two branches `main` and `prod`. The CI/CD is (I hope) configured in a way that the dump only gets loaded in the corresponding environment

**Comment by danielegobbetti** [comment]
> I don't know how the DB is initialized in the first place, is the admin user generated by django on first startup? In that case it should even be fine, since the dump gets loaded afterwards.

The admin user is created from the commandline via a manage.py incantation. The app is perfectly able to work without an admin user (read: with an empty auth_user table), I don't know what would happen if the table was missing though.

> The `dump.sql` is a single one, the idea is that what's in prod and testing is managed by the two branches `main` and `prod`. The CI/CD is (I hope) configured in a way that the dump only gets loaded in the corresponding environment

I missed that part, sorry.

**Comment by clezag** [comment]
But the tables should be generated by django (or whatever the ORM is) on first startup, right? 
Which would be before the dump is loaded, so we could already be fine.

Personally I'm also fine if the first startup requires some manual extra work, as long as it's documented.
